# Use an official Python base image from the Docker Hub
FROM python:3.10-slim AS autogpt-base

# Install browsers
RUN apt-get update && apt-get install -y \
    chromium-driver firefox-esr ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install utilities
RUN apt-get update && apt-get install -y \
    curl jq wget git build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install TA lib
RUN wget https://jaist.dl.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz && \
    tar -xvf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib/ && \
    ./configure --prefix=/usr && \
    make && \
    make install

# release build -> include bare minimum
FROM autogpt-base as autogpt-release

# Set environment variables
ENV PIP_NO_CACHE_DIR=yes \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Install the required python packages globally
ENV PATH="$PATH:/root/.local/bin"
COPY requirements.txt .

RUN pip install --upgrade pip
RUN sed -i '/Items below this point will not be included in the Docker Image/,$d' requirements.txt && \
	pip install --no-cache-dir -r requirements.txt

WORKDIR /app
ONBUILD COPY autogpt ./autogpt
ONBUILD COPY scripts ./scripts
ONBUILD COPY plugins ./plugins
ONBUILD COPY chrome_settings ./chrome_settings

FROM autogpt-release AS auto-gpt

COPY gcloud-run.sh .
# TODO: move
COPY heroku/env .env.base
COPY heroku/h_plugins_config.yaml .
COPY heroku/prompt_settings.yaml .
COPY heroku/dummy_server.py .

CMD ["./gcloud-run.sh"]
